name: My Mastodon Digest 
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run digest
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
          MASTODON_USERNAME: ${{ secrets.MASTODON_USERNAME }}
        run: |
          python run.py -n 24 -s SimpleWeighted -t lax
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.2
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.SMTP_SERVER}}
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 587
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: ${{secrets.MAIL_RECIPIENT}}
          # Required sender full name (address can be skipped):
          from: Mastodon Mail Digest <petersonjm1+mastodon_digest@gmail.com>
          # Optional HTML body read from file:
          html_body: file://render/index.html
          # Optional recipient of the email response:
          reply_to: petersonjm1+mastodon_digest@gmail.com

